name: ICPC compile

on:
  push:
    branches: test-ci
  pull_request:
    branches: test-ci

jobs:
  build:

    runs-on: ubuntu-18.04
    container: jojoelfe/cistem_ci



    steps:
    - uses: actions/checkout@v2
    - name: regenerate_project
      run: ./regenerate_project.b
    - name: set path
      run: | 
        echo "/opt/intel/oneapi/compiler/2021.4.0/linux/bin/intel64" >> $GITHUB_PATH
        echo "CPATH=/opt/intel/oneapi/vpl/2021.6.0/include:/opt/intel/oneapi/tbb/2021.4.0/env/../include:/opt/intel/oneapi/mpi/2021.4.0//include:/opt/intel/oneapi/mkl/2021.4.0/include:/opt/intel/oneapi/ippcp/2021.4.0/include:/opt/intel/oneapi/ipp/2021.4.0/include:/opt/intel/oneapi/dpl/2021.5.0/linux/include:/opt/intel/oneapi/dnnl/2021.4.0/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/dev-utilities/2021.4.0/include:/opt/intel/oneapi/dal/2021.4.0/include:/opt/intel/oneapi/compiler/2021.4.0/linux/include:/opt/intel/oneapi/ccl/2021.4.0/include/cpu_gpu_dpcpp" >> $GITHUB_ENV
    - name: configure
      run: |
        echo "$PATH"
        mkdir -p build/icpc 
        cd build/icpc 
        CXX=icpc CC=icc ../../configure  --enable-experimental --enable-staticmode --enable-openmp  --with-wx-config=wx-config  --enable-samples
    - name: make
      run: |
        cd build/icpc
        make -j4
    - name: setup python
      run: |
        cd build/icpc
        PYTHON_BUILD_DEFINITIONS="../../src/pycistem/pybuild/" bash ../../src/pycistem/pybuild/python-build 3.9.6  ./python/
        ./python/bin/python -m venv pycistem-venv
        pycistem-venv/bin/python -m pip install -r ../../src/pycistem/requirements.txt 
    - name: build python extension
      run: |
        cd build/icpc
        cp ../../src/pycistem/setup.py ./ 
        cp ../../src/pycistem/src/main.cpp ./src/
        pycistem-venv/bin/python setup.py build_ext --inplace

    - name: test console_test
      run: "! build/icpc/src/console_test | grep FAILED"
    - name: test samples_functional_testing
      run: "! build/icpc/samples_functional_testing"
    - name: test pytest
      run: build/icpc/pycistem-venv/bin/python -m pytest test/
    - name: Create binary artifact
      uses: actions/upload-artifact@v2
      with: 
        name: cistem_binaries
        path: build/icpc/src
