name: ICPC compile

on:
  push:
    branches: test-ci
  pull_request:
    branches: test-ci

jobs:
  build:

    runs-on: centos6



    steps:
    - uses: actions/checkout@v2
    - name: Cache wx
        uses: actions/cache@v2
        env:
          cache-name: cache-wx
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/wx
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/wx/') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - name: Install Intel
      run: |
        sudo rpm --import https://yum.repos.intel.com/2019/setup/RPM-GPG-KEY-intel-psxe-runtime-2019
        sudo rpm -Uhv https://yum.repos.intel.com/2019/setup/intel-psxe-runtime-2019-reposetup-1-0.noarch.rpm
        sudo yum install intel-icc-runtime*
    - name: configure
      run:  CC=icc CXX=icpc ./configure  --enable-experimental --enable-staticmode --enable-openmp  --with-wx-config=${wx_dir}INTEL/bin/wx-config
    - name: make
      run: make
    