name: ICPC compile

on:
  push:
    branches: test-ci
  pull_request:
    branches: test-ci

jobs:
  build:

    runs-on: ubuntu-18.04
    container: jojoelfe/cistem_ci



    steps:
    - uses: actions/checkout@v2
    - name: regenerate_project
      run: ./regenerate_project.b
    - name: configure
      run: mkdir -p build/icpc && cd build/icpc && CXX=/opt/intel/oneapi/compiler/2021.4.0/linux/bin/intel64/icpc CC=/opt/intel/oneapi/compiler/2021.4.0/linux/bin/intel64/icc CXXFLAGS=-fPIC CFLAGS=-fPIC  ../../configure  --enable-experimental --enable-staticmode --enable-openmp  --with-wx-config=wx-config 
    - name: make
      run: cd build/icpc && make -j4
    - name: Create binary artifact
      uses: actions/upload-artifact@v2
      with: 
        name: cistem_binaries
        path: build/icpc/src
