name: ICPC compile

on:
  push:
    branches: test-ci
  pull_request:
    branches: test-ci

jobs:
  build:

    runs-on: ubuntu-18.04



    steps:
    - uses: actions/checkout@v2
    - name: Cache wx
      uses: actions/cache@v2
      env:
        cache-name: cache-wx
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/wx
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/wx/') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Intel
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        sudo apt-get install intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-mkl intel-oneapi-mkl-devel
        source /opt/intel/oneapi/setvars.sh
        printenv >> $GITHUB_ENV
        echo "CXX=icpc" >> $GITHUB_ENV
        echo "CC=icc" >> $GITHUB_ENV
    - name: configure
      run:  CC=icc CXX=icpc ./configure  --enable-experimental --enable-staticmode --enable-openmp  --with-wx-config=~/wx/bin/wx-config
    - name: make
      run: make
    